export const productDB = [
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Small Fresh Pants",
    productPrice: "310.00",
    productQuantity: 9329,
    productSize: "9",
    productCode: "KMF",
    productID: "1",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Sleek Concrete Tuna",
    productPrice: "764.00",
    productQuantity: 90910,
    productSize: "2",
    productCode: "AMD",
    productID: "2",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Fantastic Fresh Mouse",
    productPrice: "159.00",
    productQuantity: 38295,
    productSize: "6",
    productCode: "BAM",
    productID: "3",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Fantastic Steel Salad",
    productPrice: "240.00",
    productQuantity: 37883,
    productSize: "5",
    productCode: "TJS",
    productID: "4",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Fantastic Fresh Shoes",
    productPrice: "925.00",
    productQuantity: 12064,
    productSize: "5",
    productCode: "USD",
    productID: "5",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Electronic Metal Gloves",
    productPrice: "160.00",
    productQuantity: 14612,
    productSize: "3",
    productCode: "SCR",
    productID: "6",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Fantastic Fresh Fish",
    productPrice: "688.00",
    productQuantity: 40933,
    productSize: "1",
    productCode: "TMT",
    productID: "7",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Recycled Metal Computer",
    productPrice: "522.00",
    productQuantity: 87196,
    productSize: "7",
    productCode: "BGN",
    productID: "8",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Tasty Plastic Shoes",
    productPrice: "433.00",
    productQuantity: 46615,
    productSize: "1",
    productCode: "BND",
    productID: "9",
  },
  {
    Image: "https://loremflickr.com/640/480/fashion",
    productName: "Fantastic Wooden Keyboard",
    productPrice: "868.00",
    productQuantity: 43033,
    productSize: "6",
    productCode: "MOP",
    productID: "10",
  },
];
